### ISSUE TITLE
This doesn't work anymore, any plans to update it? 

### ISSUE THREAD

**Issue by DJCool1** [metaperl/signalstart-analysis#1]
Greetings,

This code is out of date - scrappy notes "unknown command: crawl" - this command seems to be depreciated. Any plans to update this code?

**Comment by metaperl** [comment]
Hi, I dont have any plans to update this code.

**Comment by DJCool1** [comment]
I emailed you at your jobs gmail on 6/20.

**Comment by metaperl** [comment]
yeah my main email is terrence.brannon@gmail.com - I dont read that one frequently.
